# Generated by Django 5.1 on 2024-08-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_skill_created_at_alter_skill_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
