# Generated by Django 5.1 on 2024-08-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_department_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dept_supervisors',
            field=models.ManyToManyField(blank=True, related_name='department_super', to='API.employeedetails'),
        ),
    ]
